export const expRegulares = {
  onlyUppercase: /^[A-ZÁÉÍÓÚÑÜ\s]+$/,
  uppercaseAndNumber: /^[A-ZÁÉÍÓÚÑÜ0-9\s]+$/,
  onlyText: /^[a-zA-ZÁÉÍÓÚÑÜáéíóúñü\s]+$/,
  TextAndNumber: /^[a-zA-ZÁÉÍÓÚÑÜáéíóúñü0-9\s]+$/,
  onlyAddress: /^[a-zA-ZÁÉÍÓÚÑÜáéíóúñü0-9#,\s.-]+$/,
  condorTextID: /^[SN0-9\s]+$/,
  onlyNumber: /^[0-9\s]+$/,
  camelCase: /^[A-Z][a-z]+(?:[A-Z][a-z]+)*$/,
  numberAndHyphen: /^(\d+-)*\d+$/,
  cardOfBank: /^(?:\d{4}-){3}\d{4}$|^\d{16}$/,
  numberPhone: /^(\+?\d[\d\s-]*)(\s*,\s*(\+?\d[\d\s-]*))*$/,
  numberPhoneSlash: /^(\+?\d[\d\s-]*)(\/\+?\d[\d\s-]*)*$/,
  nickName: /^[a-zA-Z0-9_-]{3,15}$/,
  ip: /^(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)){3}$/,
  email: /^[a-zA-Z0-9_]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,}$/,
  codeThreeLettersHyphenNumbers: /^[A-Z]{3}-\d+$/,
  exchangeRate: /^\d+(?:.\d+)?$/,
}
