export const STRINGS = {
  tittleSite: 'PEAJESIG',
  textConfig: 'Configuración',
  gestion: 'Gestión',
  gestionPeaje: 'Acciones de peaje',
  errorMessage: 'Ha ocurrido un error, por favor intenta de nuevo.',
  adicionarModelo: 'Adicionar modelo',
  actualizarDatos: 'Actualizar datos',
  ExpandirContrear: 'Expandir o contraer nodos',
  renameCategoria: 'Renombrar categoría',
  deleteCategoria: 'Eliminar categoría',
  addCategoria: 'Adicionar categoría',
  addProvincia: 'Adicionar provincia',
  editProvincia: 'Modificar provincia',
  deleteProvincia: 'Eliminar provincia',
  addMunicipio: 'Adicionar municipio',
  editMunicipio: 'Modificar municipio',
  deleteMunicipio: 'Eliminar municipio',
  addOrganismo: 'Adicionar organismo',
  editOrganismo: 'Modificar organismo',
  deleteOrganismo: 'Eliminar organismo',
  PreguntaDeleteProvincia: '¿Está seguro de eliminar la provincia: ',
  PreguntaDeleteMunicipio: '¿Está seguro de eliminar el municipio ',
  PreguntaDeleteOrganismo: '¿Está seguro de eliminar el organismo: ',
  category: 'Categoría',
  addModelo: 'Adicionar modelo',
  gestion_Bd_datos: 'Gestionar fuente de datos',
  denominacion: 'Denominación',
  descripcion: 'Descripción',
  cmp_modelo: 'Campos del modelo',
  nombre: 'Nombre',
  nombre_abreviado: 'Sigla',
  nombre_prov: 'Nombre provincia',
  nombre_mun: 'Nombre municipio',
  codigo_prov: 'Código provincia',
  codigo_mun: 'Código municipio',
  nombre_org: 'Nombre organismo',
  codigo_org: 'Código organismo',
  tipo: 'Tipo',
  obigatorio: 'Obligatorio',
  multiselección: 'Multiselección',
  record_page: 'Registros por página',
  oculto: 'Oculto',
  filtro: 'Filtro',
  close: 'Cerrar',
  save: 'Guardar',
  access: 'Aceptar',
  cancel: 'Cancelar',
  dir_provincia: 'gest_provincia',
  name_provincia: 'Provincia',
  name_municipio: 'Municipio',
  name_organismo: 'Organismo',
  provinciaLowercase: 'provincia',
  municipioLowercase: 'municipio',
  organismoLowercase: 'organismo',
  search: 'Buscar...',
  desabilitar: 'disabled',

  // Agrega más textos según sea necesario
}
